### PR TITLE
Fixed deprecations on activationEvents and stylesheets/

### PR DESCRIPTION
**Pull request by feelic**
The latest version of atom marks "activationEvents" and stylesheets as deprecated 
(cf issues https://github.com/guileen/project-switcher/issues/15 and https://github.com/guileen/project-switcher/issues/14 )

### CODE REVIEW

**Comment by ricardofbarros** [comment]
@feelic It's giving an error, you should on package.json do the following:

```json
...
 "activationCommands": {
    "atom-text-editor": ["project-switcher:toggle"]
  },
...
```

**Comment by ricardofbarros** [comment]
Please update your PR with those changes so I can merge it! Thank you :smile:

**Comment by feelic** [comment]
it's updated !

**Comment by ricardofbarros** [comment]
Thank you :smile:

**Comment by ricardofbarros** [comment]
and pushed a new version :)

**Comment by feelic** [comment]
Nice thanks !

**Pull request merged**
