### PR TITLE
Fix utils.getSiblingProject

### PR DESCRIPTION
**Pull request by ricardofbarros**
As is the current code it doesn't work on atom v0.181.0.

Issue link #9

### CODE REVIEW

**Comment by stjohnjohnson** [comment]
@guileen please take a look at this PR.  It's completely breaking this package now.

**Comment by ricardofbarros** [comment]
Did the author abandoned this project?

**Comment by guileen** [comment]
@ricardofbarros @stjohnjohnson 
I am use vim again, so I am not using atom any more, if you have interesting to maintain this project, I would like to add you guys to the collabrators

**Comment by ricardofbarros** [comment]
Sure, that would be great for me

**Comment by guileen** [comment]
I have add you to collaborators, but I don't know how to grant atom package publish permission to you.

**Comment by ricardofbarros** [comment]
Atom somehow knowns I'm a collaborator and I can publish on your behalf. So no problem.

**Pull request merged**
